### ISSUE TITLE
Failed to start account creation

### ISSUE THREAD

**Issue by s0gray** [hqdchapman/steam-autoreg#2]
Python 3.8 from Microsfot Store
Windows 11

Set capture service in popup
Press button 'Начать'

**File "main.py", line 841, in start_process
    steamreg.set_captcha_service()
AttributeError: module 'steamreg' has no attribute 'set_captcha_service'**

**Comment by s0gray** [comment]
root.mainloop()
 must be moved to the end, otherwise execution freeze and 'steamreg' interpreted as module name, not class instance

**Comment by sheswallowedburningcoals** [comment]
Please make a pull request

**Comment by hqdchapman** [comment]
I thnik the software is needed to be translated into english as well

**Comment by hqdchapman** [comment]
> ```
> root.mainloop()
> ```
> 
> must be moved to the end, otherwise execution freeze and 'steamreg' interpreted as module name, not class instance

yes, it gets frozen because of UI frame ticks. As far as logging is concerned, I think it had better place. before class creation

**Comment by hqdchapman** [comment]
resolved in the last commit
